name = "Hiligaynon"
version = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Hiligaynon spellchecker"
hil = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Hiligaynon, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
hil = "TRANSLATE: A spellchecker for Hiligaynon, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.hil"

[windows]
system_product_code = "{5C844BF8-2DF2-41C4-AFE0-345F73CE0449}_is1"
