template = "https://github.com/giellalt/template-lang-und"
rev_id = 297
template_sha = "52b95ba1a20c2050f5f989acd657a0747a9d7fe3"

[replacements]
__GLOTTOLOG_ID__ = "hili1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-hil"
__UND2C__ = "hil"
__UNDEFINED__ = "Hiligaynon"
__UND__ = "hil"
