template = "https://github.com/giellalt/template-lang-und"
rev_id = 317
template_sha = "3d0bcfa8020a96bc946192565f7e92213470a110"

[replacements]
__GLOTTOLOG_ID__ = "hili1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-hil"
__UND2C__ = "hil"
__UNDEFINED__ = "Hiligaynon"
__UND__ = "hil"
