template = "https://github.com/giellalt/template-lang-und"
rev_id = 313
template_sha = "818c033010c3b7b906621cdeca79061f50bd93ed"

[replacements]
__GLOTTOLOG_ID__ = "hili1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-hil"
__UND2C__ = "hil"
__UNDEFINED__ = "Hiligaynon"
__UND__ = "hil"
